server:
  port: 8080
  servlet:
    context-path: '/doctor-plus'
spring:
  application:
    name: doctor-plus-gerenciador
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    expose-spring-macro-helpers: true

# /api-docs endpoint custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  show-actuator: false

doctor-plus:
  security:
    properties:
      white-list: ["/h2-console/**", "/swagger-ui/**","/v3/api-docs/**", "/swagger-ui.html/**", "/api-docs", "/api-docs/**", "/usuario/profissional", "/endereco/**", "/autenticacao/**", "/autenticacao"]
  feign:
    client:
      via-plus:
        name: VIA-PLUS
        url: https://viacep.com.br/ws/


