CREATE TABLE ROLES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    DESCRICAO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
    );

CREATE TABLE ORGANIZACOES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    NOME_SISTEMA VARCHAR(100) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE
    );


CREATE TABLE ENDERECOS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    CEP VARCHAR(9) NOT NULL,
    NUMERO VARCHAR(100) NOT NULL,
    COMPLEMENTO varchar(100)
    );

CREATE TABLE USUARIOS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_ENDERECO BIGINT NOT NULL,
    ID_ORGANIZACAO BIGINT NOT NULL,
    ID_ROLE BIGINT NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    NOME VARCHAR(50) DEFAULT NOT NULl,
    SOBRENOME VARCHAR(50) DEFAULT NULL,
    SENHA VARCHAR(250) DEFAULT NULL,
    CPF varchar(14) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    STATUS varchar(15) NOT NULL,
    CODIGO_VERIFICACAO char(4) NOT NULL,
      CONSTRAINT FK_USUARIO_ORGANIZACAO FOREIGN KEY (`ID_ORGANIZACAO`) REFERENCES ORGANIZACOES(`ID`),
      CONSTRAINT FK_USUARIO_FUNCIONALIDADE FOREIGN KEY (`ID_ROLE`) REFERENCES ROLES(`ID`),
      CONSTRAINT FK_USUARIO_ENDERECOS FOREIGN KEY (`ID_ENDERECO`) REFERENCES ENDERECOS(`ID`)
    );

