CREATE TABLE FUNCIONALIDADES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    DESCRICAO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
    );

CREATE TABLE ORGANIZACOES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    NOME VARCHAR(100) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE
    );

CREATE TABLE USUARIOS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    NOME VARCHAR(50) DEFAULT NULL,
    SENHA VARCHAR(250) DEFAULT NULL,
    ID_ORGANIZACAO BIGINT NOT NULL,
    ID_FUNCIONALIDADE BIGINT NOT NULL,
      CONSTRAINT FK_USUARIO_ORGANIZACAO FOREIGN KEY (`ID_ORGANIZACAO`) REFERENCES ORGANIZACOES(`ID`),
      CONSTRAINT FK_USUARIO_FUNCIONALIDADE FOREIGN KEY (`ID_FUNCIONALIDADE`) REFERENCES FUNCIONALIDADES(`ID`)
    );

