INSERT INTO FUNCIONALIDADES (DESCRICAO, TIPO) VALUES('FUNCIONALIDADE DO ADMINISTRADOR DO SISTEMA', 'ROLE_ADMINISTRATIVO');
INSERT INTO FUNCIONALIDADES (DESCRICAO, TIPO) VALUES('FUNCIONALIDADE DO PROFISSIONAL DE SAUDE DO SISTEMA', 'ROLE_PROFISSIONAL_SAUDE');
INSERT INTO FUNCIONALIDADES (DESCRICAO, TIPO) VALUES('FUNCIONALIDADE DA SECRETARIA DO SISTEMA', 'ROLE_SECRETARIA');